name: Validate wih hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "32 1 * * THU"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "home-assistant/actions/hassfest@master"
